added role object and its functions
TheArchNemesis/Skillz2019 pull request #7
Opened 2019-01-30 09:08 UTC by guyrif1

Role object for anything makes it easier to use

2019-01-30 09:09 UTC, guyrif1 commented
YOU FOOL! THIS IS NOT JAVA! FIX YOUR FUNCTION NAMES OR DIE BRAINLESS IDIOT!

2019-02-03 13:15 UTC, ScarletMetal requested changes

2019-02-03 13:15 UTC, TheArchNemesis commented on GoblinSabotageSquad/role.py
> +
why?

2019-02-03 13:15 UTC, TheArchNemesis commented on GoblinSabotageSquad/role.py
> +    global role
this should not be global, this should be stored in self

2019-02-03 13:15 UTC, TheArchNemesis commented on GoblinSabotageSquad/role.py
> +        if (roleB == self):
`return roleb == self.role`

2019-02-03 13:15 UTC, TheArchNemesis commented on GoblinSabotageSquad/role.py
> +        if(role == "Defender"):
`return role == "Defender"`

2019-02-03 13:15 UTC, TheArchNemesis commented on GoblinSabotageSquad/role.py
> +        global role
you know

2019-02-03 13:15 UTC, TheArchNemesis commented on GoblinSabotageSquad/role.py
> +        if(role == "Portal"):
you know

2019-02-03 13:15 UTC, TheArchNemesis commented on GoblinSabotageSquad/role.py
> +        global role
y k

2019-02-03 13:15 UTC, TheArchNemesis commented on GoblinSabotageSquad/role.py
> +        global role
y k

2019-02-07 07:12 UTC, ScarletMetal approved these changes

2019-02-07 07:12 UTC, merged